# Generated by Django 5.0.6 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fullname', models.CharField(max_length=30)),
                ('form_email', models.EmailField(max_length=30)),
                ('form_number', models.BigIntegerField(max_length=12)),
                ('form_choice', models.CharField(max_length=200)),
            ],
        ),
    ]
