# Generated by Django 5.0.6 on 2024-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_formdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_number',
            field=models.BigIntegerField(),
        ),
    ]
