# Generated by Django 5.0.6 on 2024-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_formdata', '0002_alter_form_form_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form_choice',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_number',
            field=models.CharField(max_length=50),
        ),
    ]
