# Generated by Django 5.0.6 on 2024-07-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ci_formdata', '0004_enquiry_delete_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fullname', models.CharField(max_length=30)),
                ('form_email', models.CharField(max_length=30)),
                ('form_number', models.CharField(max_length=50)),
                ('form_choice', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
