# Generated by Django 5.0.6 on 2024-07-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ci_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
    ]
